version: "3.8"

services:
  prefect-server:
    image: scanfleet-prefect-server
    container_name: prefect-server
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        GLOBAL_INDEX: "${GLOBAL_INDEX}"
        GLOBAL_INDEX_URL: "${GLOBAL_INDEX_URL}"
    environment:
      - PREFECT_API_URL=http://localhost:4200
      - PREFECT_HOME=/opt/prefect
    ports:
      - "4200:4200"  # Prefect UI
    volumes:
      - prefect-data:/opt/prefect
    restart: always
    networks:
      - scannet

volumes:
  prefect-data:

networks:
  scannet:
    driver: bridge
