services:
  prefect-worker:
    image: scanfleet-prefect-worker
    container_name: prefect-worker
    build:
      context: .
      dockerfile: Dockerfile.prefect-worker
      args:
        GLOBAL_INDEX: "${GLOBAL_INDEX}"
        GLOBAL_INDEX_URL: "${GLOBAL_INDEX_URL}"
    env_file:
      - .env  # Load variables from .env file
    environment:
      - PREFECT_API_URL=http://192.168.1.188:4200/api
      - PREFECT_HOME=/home/prefect
      - WORK_POOL=${WORK_POOL}
      - GLOBAL_INDEX=${GLOBAL_INDEX}
      - GLOBAL_INDEX_URL=${GLOBAL_INDEX_URL}
    restart: always
    networks:
      - scan_fleet_scannet  # Ensure it matches the actual network name

networks:
  scan_fleet_scannet:
    external: true  # Worker must use the same network as Prefect Server
