FROM scanfleet-base:latest

USER prefect

ENV FLOW_GIT_STORAGE=${FLOW_GIT_STORAGE}
ENV FLOW_GIT_BRANCH=${FLOW_GIT_BRANCH}

WORKDIR $PREFECT_HOME

# Set working directory
WORKDIR /home/prefect

# Copy worker entrypoint script with correct ownership
COPY --chown=prefect:prefect worker-entrypoint.sh /usr/local/bin/worker-entrypoint.sh

# Ensure the entrypoint script is executable
RUN chmod +x /usr/local/bin/worker-entrypoint.sh

# Set entrypoint
ENTRYPOINT ["/usr/local/bin/worker-entrypoint.sh"]
