services:
  prefect-server:
    image: scanfleet-prefect-server
    container_name: prefect-server
    build:
      context: .
      dockerfile: Dockerfile.prefect-server
      args:
        GLOBAL_INDEX: "${GLOBAL_INDEX}"
        GLOBAL_INDEX_URL: "${GLOBAL_INDEX_URL}"
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL}
      - PREFECT_API_DATABASE_CONNECTION_URL=${PREFECT_API_DATABASE_CONNECTION_URL}
      - GLOBAL_INDEX=${GLOBAL_INDEX}
      - GLOBAL_INDEX_URL=${GLOBAL_INDEX_URL}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_SERVICE_NAME=prefect-server
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
    ports:
      - "4200:4200"
    volumes:
      - prefect-data:${CONTAINER_HOME}
    restart: always
    networks:
      - scannet

volumes:
  prefect-data:

networks:
  scannet:
    driver: bridge