FROM scanfleet-base:latest

# Set Prefect API URL explicitly
ENV PREFECT_API_URL="http://0.0.0.0:4200/api"

# Expose Prefect UI port
EXPOSE 4200

# Set working directory
WORKDIR /home/prefect

# Default command to start Prefect Server
CMD ["prefect", "server", "start", "--host", "0.0.0.0"]
