services:
  prefect-worker:
    image: scanfleet-prefect-worker
    build:
      context: .
      dockerfile: Dockerfile.prefect-worker
      args:
        GLOBAL_CERT: ${GLOBAL_CERT}
        GLOBAL_INDEX: ${GLOBAL_INDEX}
        GLOBAL_INDEX_URL: ${GLOBAL_INDEX_URL}
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    tmpfs:
      - /home/prefect/cloned_repositories:size=20G,mode=1777,exec
      - /home/prefect/logs:size=500M,mode=1777,uid=${HOST_UID},gid=${HOST_GID},exec
      - /home/prefect/output:size=500M,mode=1777,exec
    labels:
      - "worker_pool=${WORK_POOL}"
      - "worker_instance=${INSTANCE}"
    environment:
      PREFECT_API_URL: ${PREFECT_API_URL}
      WORK_POOL: ${WORK_POOL}  # Must be provided at runtime
      INSTANCE: ${INSTANCE}    # Must be provided at runtime
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
      RULESET_MAPPING_FILE: ${RULESET_MAPPING_FILE}
      METRICS_DATABASE_USER: ${METRICS_DATABASE_USER}
      METRICS_DATABASE_PASSWORD: ${METRICS_DATABASE_PASSWORD}
      METRICS_DATABASE_HOST: ${METRICS_DATABASE_HOST}
      METRICS_DATABASE_PORT: ${METRICS_DATABASE_PORT}
      METRICS_DATABASE_NAME: ${METRICS_DATABASE_NAME}
      TRIVYIGNORE_TEMPLATE: ${TRIVYIGNORE_TEMPLATE}
      SYFT_CONFIG_PATH: ${SYFT_CONFIG_PATH}
      GRYPE_CONFIG_PATH: ${GRYPE_CONFIG_PATH}
      SEMGREP_CONFIG_DIR: ${SEMGREP_CONFIG_DIR}
      BITBUCKET_HOSTNAME: ${BITBUCKET_HOSTNAME}
      GITLAB_HOSTNAME: ${GITLAB_HOSTNAME}
      KANTRA_RULESETS: ${KANTRA_RULESETS}
      KANTRA_OUTPUT_ROOT: /home/prefect/output
      HTTP_PROXY_HOST: "${HTTP_PROXY_HOST:-}"
      HTTP_PROXY_PORT: "${HTTP_PROXY_PORT:-}"
      HTTP_PROXY_USER: "${HTTP_PROXY_USER:-}"
      HTTP_PROXY_PASSWORD: "${HTTP_PROXY_PASSWORD:-}"
      TRUSTSTORE_PATH: "${TRUSTSTORE_PATH:-}"
      TRUSTSTORE_PASSWORD: "${TRUSTSTORE_PASSWORD:-}"
      DEFAULT_PROCESS_TIMEOUT: ${DEFAULT_PROCESS_TIMEOUT}
    restart: always
    volumes:
      - ${SSH_KEYS_PATH}:/tmp/keys/id_ed25519:ro,Z
      - ${SSH_KEYS_PUB_PATH}:/tmp/keys/id_ed25519.pub:ro,Z
      - ${SSH_KNOWN_HOSTS_PATH}:/tmp/keys/known_hosts:ro,Z
      - ${USER_HOME}/java.cacerts:/tmp/keys/java.cacerts:ro,Z
      - ${USER_HOME}/tls-ca-bundle.pem:/tmp/keys/tls-ca-bundle.pem:ro,Z
      - ${GRADLE_CACHE_PATH}:/home/prefect/.gradle
      - ${M2_CACHE_PATH}:/home/prefect/.m2
    networks:
      - scan_fleet_scannet

networks:
  scan_fleet_scannet:
    external: true
