FROM scanfleet-base:latest

# Set Prefect API URL explicitly
ENV PREFECT_DB_PATH="/home/prefect/.prefect/orion.db"

# Ensure SQLite database directory exists and is writable
RUN mkdir -p /home/prefect/.prefect && \
    chown -R prefect:prefect /home/prefect/.prefect && \
    chmod -R 777 /home/prefect/.prefect

# Expose Prefect UI port
EXPOSE 4200

# Set working directory
WORKDIR /home/prefect

# Default command to start Prefect Server
CMD ["prefect", "server", "start", "--host", "0.0.0.0"]
