services:
  prefect-server:
    image: scanfleet-prefect-server
    container_name: prefect-server
    build:
      context: .
      dockerfile: Dockerfile.prefect-server
      args:
        GLOBAL_INDEX: "${GLOBAL_INDEX}"
        GLOBAL_INDEX_URL: "${GLOBAL_INDEX_URL}"
        GLOBAL_INDEX_DOWNLOAD: "${GLOBAL_INDEX_DOWNLOAD}"
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL}
      - PREFECT_API_DATABASE_CONNECTION_URL=${PREFECT_API_DATABASE_CONNECTION_URL}
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - GLOBAL_INDEX=${GLOBAL_INDEX}
      - GLOBAL_INDEX_URL=${GLOBAL_INDEX_URL}
    ports:
      - "0.0.0.0:4200:4200"
    volumes:
      - prefect-data:${CONTAINER_HOME}
    restart: always
    networks:
      - scannet

volumes:
  prefect-data:

networks:
  scannet:
    driver: bridge
