services:
  prefect-server:
    image: scanfleet-prefect-server
    container_name: prefect-server
    build:
      context: .
      dockerfile: Dockerfile.prefect-server
      args:
        GLOBAL_INDEX: "${GLOBAL_INDEX}"
        GLOBAL_INDEX_URL: "${GLOBAL_INDEX_URL}"
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL}
      - GLOBAL_INDEX=${GLOBAL_INDEX}
      - GLOBAL_INDEX_URL=${GLOBAL_INDEX_URL}
    ports:
      - "4200:4200"  # Prefect UI
    volumes:
      - prefect-data:/home/prefect
    restart: always
    networks:
      - scannet

volumes:
  prefect-data:

networks:
  scannet:
    driver: bridge