services:
  prefect-worker:
    image: scanfleet-prefect-worker
    build:
      context: .
      dockerfile: Dockerfile.prefect-worker
      args:
        GLOBAL_CERT: ${GLOBAL_CERT}
        GLOBAL_INDEX: ${GLOBAL_INDEX}
        GLOBAL_INDEX_URL: ${GLOBAL_INDEX_URL}
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        TOOLS_TARBALL_URL: ${TOOLS_TARBALL_URL}
        NVM_VERSION: ${NVM_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        NVM_NODEJS_ORG_MIRROR: ${NVM_NODEJS_ORG_MIRROR}
        NVM_PRIVATE_REPO: ${NVM_PRIVATE_REPO}
    tmpfs:
      - ${CONTAINER_HOME}/cloned_repositories:size=10G,mode=1777,exec
      - ${CONTAINER_HOME}/logs:size=500M,mode=1777,uid=${HOST_UID},gid=${HOST_GID},exec
      - ${CONTAINER_HOME}/output:size=500M,mode=1777,exec
    labels:
      - "worker_pool=${WORK_POOL}"
      - "worker_instance=${INSTANCE}"
    environment:
      CONTAINER_HOME: ${CONTAINER_HOME}
      PREFECT_HOME: ${CONTAINER_HOME}
      PREFECT_API_URL: ${PREFECT_API_URL}
      WORK_POOL: ${WORK_POOL}  # Must be provided at runtime
      INSTANCE: ${INSTANCE}    # Must be provided at runtime
      RULESET_MAPPING_FILE: ${RULESET_MAPPING_FILE}
      METRICS_DATABASE_USER: ${METRICS_DATABASE_USER}
      METRICS_DATABASE_PASSWORD: ${METRICS_DATABASE_PASSWORD}
      METRICS_DATABASE_HOST: ${METRICS_DATABASE_HOST}
      METRICS_DATABASE_PORT: ${METRICS_DATABASE_PORT}
      METRICS_DATABASE_NAME: ${METRICS_DATABASE_NAME}
      TRIVYIGNORE_TEMPLATE: ${TRIVYIGNORE_TEMPLATE}
      SEMGREP_CONFIG_DIR: ${SEMGREP_CONFIG_DIR}
      SEMGREP_RULES: ${SEMGREP_RULES}
      BITBUCKET_HOSTNAME: ${BITBUCKET_HOSTNAME}
      GITLAB_HOSTNAME: ${GITLAB_HOSTNAME}
      HTTP_PROXY_HOST: "${HTTP_PROXY_HOST:-}"
      HTTP_PROXY_PORT: "${HTTP_PROXY_PORT:-}"
      HTTP_PROXY_USER: "${HTTP_PROXY_USER:-}"
      HTTP_PROXY_PASSWORD: "${HTTP_PROXY_PASSWORD:-}"
      NO_PROXY: ${NO_PROXY:-}
      TRUSTSTORE_PATH: "${TRUSTSTORE_PATH:-}"
      TRUSTSTORE_PASSWORD: "${TRUSTSTORE_PASSWORD:-}"
      DEFAULT_PROCESS_TIMEOUT: ${DEFAULT_PROCESS_TIMEOUT}
      PREFECT_LOGGING_LEVEL: DEBUG
      PREFECT_LOGGING_PERSISTENCE: false
      WORKER_NAME: ${WORKER_NAME}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ${SSH_KEYS_PATH}:/tmp/keys/id_ed25519:ro,Z
      - ${SSH_KEYS_PUB_PATH}:/tmp/keys/id_ed25519.pub:ro,Z
      - ${SSH_KNOWN_HOSTS_PATH}:/tmp/keys/known_hosts:ro,Z
      - ${USER_HOME}/tls-ca-bundle.pem:/etc/ssl/certs/tls-ca-bundle.pem:ro,Z
      - ${GRADLE_CACHE_PATH}:${CONTAINER_HOME}/.gradle
      - ${M2_SETTINGS_PATH}:${CONTAINER_HOME}/.m2/settings.xml
      - ${M2_CACHE_PATH}:${CONTAINER_HOME}/.m2/repository
    networks:
      - scan_fleet_scannet

networks:
  scan_fleet_scannet:
    external: true
