services:
  prefect-worker:
    image: scanfleet-prefect-worker
    container_name: prefect-worker-${WORK_POOL}-${INSTANCE}
    build:
      context: .
      dockerfile: Dockerfile.prefect-worker
      args:
        GLOBAL_INDEX: "${GLOBAL_INDEX}"
        GLOBAL_INDEX_URL: "${GLOBAL_INDEX_URL}"
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL}
      - WORK_POOL=${WORK_POOL}  # Must be provided at runtime
      - INSTANCE=${INSTANCE}  # Must be provided at runtime
      - GLOBAL_INDEX=${GLOBAL_INDEX}
      - GLOBAL_INDEX_URL=${GLOBAL_INDEX_URL}
    restart: always
    networks:
      - scan_fleet_scannet  # Worker must use the same network as Prefect Server

networks:
  scan_fleet_scannet:
    external: true