version: "3.8"

services:
  prefect-worker:
    image: scanfleet-prefect-worker
    container_name: prefect-worker
    build:
      context: .
      dockerfile: Dockerfile.prefect-worker
      args:
        GLOBAL_INDEX: "${GLOBAL_INDEX}"
        GLOBAL_INDEX_URL: "${GLOBAL_INDEX_URL}"
    environment:
      - PREFECT_API_URL=http://192.168.1.188:4200/api
      - PREFECT_HOME=/home/prefect
      #- WORK_POOL=${WORK_POOL}
      - WORK_POOL=repo-analysis-pool
      - GLOBAL_INDEX=${GLOBAL_INDEX}
      - GLOBAL_INDEX_URL=${GLOBAL_INDEX_URL}
    restart: always
    networks:
      - scannet
