services:
  submitters:
    image: scanfleet-prefect-submitters
    build:
      context: .
      dockerfile: Dockerfile.prefect-submitter
      args:
        FLOW_GIT_STORAGE: ${FLOW_GIT_STORAGE}
        FLOW_GIT_BRANCH:  ${FLOW_GIT_BRANCH}
    env_file:
      - .env
    container_name: submitters
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./logs:/var/log
