services:
  submitters:
    image: scanfleet-prefect-submitters
    build:
      context: .
      dockerfile: Dockerfile.prefect-submitter
      args:
        FLOW_GIT_STORAGE: ${FLOW_GIT_STORAGE}
        FLOW_GIT_BRANCH:  ${FLOW_GIT_BRANCH}
    environment:
      BITBUCKET_HOSTNAME: ${BITBUCKET_HOSTNAME}
      GITLAB_HOSTNAME: ${GITLAB_HOSTNAME}
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
      GITLAB_API_TOKEN: ${GITLAB_API_TOKEN}
      BITBUCKET_API_TOKEN: ${BITBUCKET_API_TOKEN}
      FLOW_GIT_STORAGE: ${FLOW_GIT_STORAGE}
      FLOW_GIT_BRANCH: ${FLOW_GIT_BRANCH}
    container_name: submitters
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ${SSH_KEYS_PATH}:/tmp/keys/id_ed25519:ro,Z
      - ${SSH_KEYS_PUB_PATH}:/tmp/keys/id_ed25519.pub:ro,Z
      - ${SSH_KNOWN_HOSTS_PATH}:/tmp/keys/known_hosts:ro,Z
      - ${USER_HOME}/tls-ca-bundle.pem:/etc/ssl/certs/tls-ca-bundle.pem:ro,Z